// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Splash.h"
#include "screens/ui_Clock.h"
#include "screens/ui_Weather.h"
#include "screens/ui_Alarm.h"
#include "screens/ui_Settings.h"
#include "screens/ui_Wifimenu.h"
#include "screens/ui_Sketchpad.h"
#include "screens/ui_SettingsNotes.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * upanim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * hour_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * min_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * sec_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * scrolldot_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_footer_lodyas_short_png);    // assets/footer_lodyas_short.png
LV_IMG_DECLARE(ui_img_check_png);    // assets/check.png
LV_IMG_DECLARE(ui_img_dark_dotted2_png);    // assets/dark_dotted2.png
LV_IMG_DECLARE(ui_img_min_new_png);    // assets/min_new.png
LV_IMG_DECLARE(ui_img_hour_new_png);    // assets/hour_new.png
LV_IMG_DECLARE(ui_img_sec_new_png);    // assets/sec_new.png
LV_IMG_DECLARE(ui_img_cloud_png);    // assets/cloud.png
LV_IMG_DECLARE(ui_img_weather_1_png);    // assets/weather_1.png
LV_IMG_DECLARE(ui_img_weather_2_png);    // assets/weather_2.png
LV_IMG_DECLARE(ui_img_weather_3_png);    // assets/weather_3.png
LV_IMG_DECLARE(ui_img_carbon_fibre_png);    // assets/carbon_fibre.png
LV_IMG_DECLARE(ui_img_565810218);    // assets/sticky-note-0.png
LV_IMG_DECLARE(ui_img_1741635428);    // assets/wi-fi_24.png
LV_IMG_DECLARE(ui_img_refresh_64_png);    // assets/refresh_64.png
LV_IMG_DECLARE(ui_img_note_png);    // assets/note.png

// FONTS
LV_FONT_DECLARE(ui_font_Number);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
