// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "ui.h"

void ui_event_wifi_item_clicked(lv_event_t * e)
{
	// Your code here
}

void ui_app_wifi_scan_refresh(lv_event_t * e)
{
	// Your code here
}

void ui_event_ConnectBtn_Clicked(lv_event_t * e)
{
	// Your code here
}
