// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_CLICK_BLUE 0
#define UI_THEME_COLOR_CLICK_RED 1
#define UI_THEME_COLOR_PANEL_BLUE 2
#define UI_THEME_COLOR_PRESSED_BLUE 3

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_click_blue[1];
extern const ui_theme_variable_t _ui_theme_alpha_click_blue[1];

extern const ui_theme_variable_t _ui_theme_color_Click_red[1];
extern const ui_theme_variable_t _ui_theme_alpha_Click_red[1];

extern const ui_theme_variable_t _ui_theme_color_panel_blue[1];
extern const ui_theme_variable_t _ui_theme_alpha_panel_blue[1];

extern const ui_theme_variable_t _ui_theme_color_Pressed_blue[1];
extern const ui_theme_variable_t _ui_theme_alpha_Pressed_blue[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
