// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_click_blue[1] = {0x4D97E3};
const ui_theme_variable_t _ui_theme_alpha_click_blue[1] = {255};

const ui_theme_variable_t _ui_theme_color_Click_red[1] = {0xF4574C};
const ui_theme_variable_t _ui_theme_alpha_Click_red[1] = {255};

const ui_theme_variable_t _ui_theme_color_panel_blue[1] = {0xD9EAF0};
const ui_theme_variable_t _ui_theme_alpha_panel_blue[1] = {255};

const ui_theme_variable_t _ui_theme_color_Pressed_blue[1] = {0x5CC9EB};
const ui_theme_variable_t _ui_theme_alpha_Pressed_blue[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

