// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _UI_COMP_DAYCELL_H
#define _UI_COMP_DAYCELL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT DayCell
#define UI_COMP_DAYCELL_DAYCELL 0
#define UI_COMP_DAYCELL_RING1 1
#define UI_COMP_DAYCELL_PANEL11 2
#define UI_COMP_DAYCELL_RING2 3
#define UI_COMP_DAYCELL_PANEL12 4
#define UI_COMP_DAYCELL_RING3 5
#define UI_COMP_DAYCELL_PANEL14 6
#define UI_COMP_DAYCELL_DATENUM 7
#define _UI_COMP_DAYCELL_NUM 8
lv_obj_t * ui_DayCell_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
