// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

// COMPONENT DayCell

lv_obj_t * ui_DayCell_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_DayCell;
    cui_DayCell = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_DayCell);
    lv_obj_set_width(cui_DayCell, 30);
    lv_obj_set_height(cui_DayCell, 30);
    lv_obj_set_align(cui_DayCell, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_DayCell, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Ring1;
    cui_Ring1 = lv_obj_create(cui_DayCell);
    lv_obj_set_width(cui_Ring1, 30);
    lv_obj_set_height(cui_Ring1, 30);
    lv_obj_set_align(cui_Ring1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Ring1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Ring1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Ring1, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Ring1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel11;
    cui_Panel11 = lv_obj_create(cui_DayCell);
    lv_obj_set_width(cui_Panel11, 26);
    lv_obj_set_height(cui_Panel11, 26);
    lv_obj_set_align(cui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel11, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Panel11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Ring2;
    cui_Ring2 = lv_obj_create(cui_DayCell);
    lv_obj_set_width(cui_Ring2, 24);
    lv_obj_set_height(cui_Ring2, 24);
    lv_obj_set_align(cui_Ring2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Ring2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Ring2, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Ring2, lv_color_hex(0x2DCBD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Ring2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel12;
    cui_Panel12 = lv_obj_create(cui_DayCell);
    lv_obj_set_width(cui_Panel12, 20);
    lv_obj_set_height(cui_Panel12, 20);
    lv_obj_set_align(cui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel12, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_Panel12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Ring3;
    cui_Ring3 = lv_obj_create(cui_DayCell);
    lv_obj_set_width(cui_Ring3, 18);
    lv_obj_set_height(cui_Ring3, 18);
    lv_obj_set_align(cui_Ring3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Ring3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Ring3, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Ring3, lv_color_hex(0xFA080E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Ring3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel14;
    cui_Panel14 = lv_obj_create(cui_DayCell);
    lv_obj_set_width(cui_Panel14, 14);
    lv_obj_set_height(cui_Panel14, 14);
    lv_obj_set_align(cui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel14, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_DateNum;
    cui_DateNum = lv_label_create(cui_DayCell);
    lv_obj_set_width(cui_DateNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_DateNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_DateNum, 0);
    lv_obj_set_y(cui_DateNum, -1);
    lv_obj_set_align(cui_DateNum, LV_ALIGN_CENTER);
    lv_label_set_text(cui_DateNum, "23");
    lv_obj_set_style_text_color(cui_DateNum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_DateNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_DateNum, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DAYCELL_NUM);
    children[UI_COMP_DAYCELL_DAYCELL] = cui_DayCell;
    children[UI_COMP_DAYCELL_RING1] = cui_Ring1;
    children[UI_COMP_DAYCELL_PANEL11] = cui_Panel11;
    children[UI_COMP_DAYCELL_RING2] = cui_Ring2;
    children[UI_COMP_DAYCELL_PANEL12] = cui_Panel12;
    children[UI_COMP_DAYCELL_RING3] = cui_Ring3;
    children[UI_COMP_DAYCELL_PANEL14] = cui_Panel14;
    children[UI_COMP_DAYCELL_DATENUM] = cui_DateNum;
    lv_obj_add_event_cb(cui_DayCell, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_DayCell, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_DayCell_create_hook(cui_DayCell);
    return cui_DayCell;
}

