// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_ALARM_H
#define UI_ALARM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Alarm
extern void ui_Alarm_screen_init(void);
extern void ui_Alarm_screen_destroy(void);
extern void ui_event_Alarm(lv_event_t * e);
extern lv_obj_t * ui_Alarm;
extern lv_obj_t * ui_Alarm_container;
extern lv_obj_t * ui_Set_alarm1;
extern void ui_event_Alarm_Comp4(lv_event_t * e);
extern lv_obj_t * ui_Alarm_Comp4;
extern lv_obj_t * ui_Alarm_Num1;
extern lv_obj_t * ui_Period2;
extern lv_obj_t * ui_Switch2;
extern void ui_event_Alarm_Comp5(lv_event_t * e);
extern lv_obj_t * ui_Alarm_Comp5;
extern lv_obj_t * ui_Alarm_Num3;
extern lv_obj_t * ui_Period3;
extern lv_obj_t * ui_Switch3;
extern void ui_event_Alarm_Comp1(lv_event_t * e);
extern lv_obj_t * ui_Alarm_Comp1;
extern lv_obj_t * ui_Alarm_Num4;
extern lv_obj_t * ui_Period4;
extern lv_obj_t * ui_Switch4;
extern void ui_event_Alarm_Comp2(lv_event_t * e);
extern lv_obj_t * ui_Alarm_Comp2;
extern lv_obj_t * ui_Alarm_Num5;
extern lv_obj_t * ui_Period1;
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_AlarmSetPanel;
extern lv_obj_t * ui_RollerMin;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_RollerHour;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label9;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

