// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_ALARM_H
#define UI_ALARM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Alarm
extern void ui_Alarm_screen_init(void);
extern void ui_Alarm_screen_destroy(void);
extern void ui_event_Alarm(lv_event_t * e);
extern lv_obj_t * ui_Alarm;
extern lv_obj_t * ui_Alarm_container;
extern lv_obj_t * ui_Set_alarm1;
extern lv_obj_t * ui_AlarmComp;
extern lv_obj_t * ui_Alarm_Num1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_AlarmSetPanel;
extern lv_obj_t * ui_RollerMin;
extern lv_obj_t * ui_RollerHour;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_AlarmSetBtn;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_AlarmDelBtn;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_NewAlarmBtn;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

