// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * ui_Alarm = NULL;
lv_obj_t * ui_Alarm_container = NULL;
lv_obj_t * ui_Set_alarm1 = NULL;
lv_obj_t * ui_AlarmComp = NULL;
lv_obj_t * ui_Alarm_Num1 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_AlarmSetPanel = NULL;
lv_obj_t * ui_RollerMin = NULL;
lv_obj_t * ui_RollerHour = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_AlarmSetBtn = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_AlarmDelBtn = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_NewAlarmBtn = NULL;
lv_obj_t * ui_Label11 = NULL;
// event funtions
void ui_event_Alarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Weather, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_Weather_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0, &ui_Settings_screen_init);
    }
}

// build funtions

void ui_Alarm_screen_init(void)
{
    ui_Alarm = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Alarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Alarm, &ui_img_dark_dotted2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Alarm, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm_container = lv_obj_create(ui_Alarm);
    lv_obj_set_width(ui_Alarm_container, lv_pct(100));
    lv_obj_set_height(ui_Alarm_container, lv_pct(100));
    lv_obj_set_align(ui_Alarm_container, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Alarm_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Set_alarm1 = lv_label_create(ui_Alarm_container);
    lv_obj_set_width(ui_Set_alarm1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Set_alarm1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Set_alarm1, 0);
    lv_obj_set_y(ui_Set_alarm1, 17);
    lv_obj_set_align(ui_Set_alarm1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Set_alarm1, "Set alarm");
    ui_object_set_themeable_style_property(ui_Set_alarm1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_Set_alarm1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_text_font(ui_Set_alarm1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmComp = lv_obj_create(ui_Alarm_container);
    lv_obj_set_height(ui_AlarmComp, 80);
    lv_obj_set_width(ui_AlarmComp, lv_pct(94));
    lv_obj_set_x(ui_AlarmComp, 0);
    lv_obj_set_y(ui_AlarmComp, 43);
    lv_obj_set_align(ui_AlarmComp, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_AlarmComp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AlarmComp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AlarmComp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AlarmComp, lv_color_hex(0x8A3200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AlarmComp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AlarmComp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_AlarmComp, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AlarmComp, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AlarmComp, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AlarmComp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AlarmComp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm_Num1 = lv_label_create(ui_AlarmComp);
    lv_obj_set_width(ui_Alarm_Num1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alarm_Num1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alarm_Num1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Alarm_Num1, "7:00");
    ui_object_set_themeable_style_property(ui_Alarm_Num1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_Alarm_Num1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_text_font(ui_Alarm_Num1, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_AlarmComp);
    lv_obj_set_width(ui_Switch2, 61);
    lv_obj_set_height(ui_Switch2, 32);
    lv_obj_set_x(ui_Switch2, -4);
    lv_obj_set_y(ui_Switch2, 11);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_radius(ui_Switch2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x9D9ED5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Switch2, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x293062), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_radius(ui_Switch2, 50, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Switch2, -3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Switch2, -3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Switch2, -3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Switch2, -3, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_AlarmSetPanel = lv_obj_create(ui_Alarm);
    lv_obj_set_width(ui_AlarmSetPanel, 240);
    lv_obj_set_height(ui_AlarmSetPanel, 320);
    lv_obj_set_align(ui_AlarmSetPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AlarmSetPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_AlarmSetPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_AlarmSetPanel, &ui_img_dark_dotted2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_AlarmSetPanel, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_tiled(ui_AlarmSetPanel, true, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_RollerMin = lv_roller_create(ui_AlarmSetPanel);
    lv_roller_set_options(ui_RollerMin, "00\n05\n10\n15\n20\n25\n30\n35\n40\n45\n50\n55", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerMin, 80);
    lv_obj_set_height(ui_RollerMin, 150);
    lv_obj_set_x(ui_RollerMin, 46);
    lv_obj_set_y(ui_RollerMin, -79);
    lv_obj_set_align(ui_RollerMin, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerMin, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerHour = lv_roller_create(ui_AlarmSetPanel);
    lv_roller_set_options(ui_RollerHour, "1", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_RollerHour, 150);
    lv_obj_set_width(ui_RollerHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_RollerHour, -48);
    lv_obj_set_y(ui_RollerHour, -79);
    lv_obj_set_align(ui_RollerHour, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerHour, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_AlarmSetPanel);
    lv_obj_set_width(ui_Panel4, 10);
    lv_obj_set_height(ui_Panel4, 10);
    lv_obj_set_x(ui_Panel4, -7);
    lv_obj_set_y(ui_Panel4, -68);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_AlarmSetPanel);
    lv_obj_set_width(ui_Panel9, 10);
    lv_obj_set_height(ui_Panel9, 10);
    lv_obj_set_x(ui_Panel9, -7);
    lv_obj_set_y(ui_Panel9, -89);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_AlarmSetPanel);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -51);
    lv_obj_set_y(ui_Label4, 25);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Hr");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFBEAE1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_AlarmSetPanel);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 45);
    lv_obj_set_y(ui_Label9, 27);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Min");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFBEAE1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmSetBtn = lv_btn_create(ui_AlarmSetPanel);
    lv_obj_set_width(ui_AlarmSetBtn, 100);
    lv_obj_set_height(ui_AlarmSetBtn, 50);
    lv_obj_set_x(ui_AlarmSetBtn, -2);
    lv_obj_set_y(ui_AlarmSetBtn, 77);
    lv_obj_set_align(ui_AlarmSetBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AlarmSetBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AlarmSetBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_AlarmSetBtn);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "SET");
    ui_object_set_themeable_style_property(ui_Label10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_Label10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmDelBtn = lv_btn_create(ui_AlarmSetPanel);
    lv_obj_set_width(ui_AlarmDelBtn, 70);
    lv_obj_set_height(ui_AlarmDelBtn, 30);
    lv_obj_set_x(ui_AlarmDelBtn, 0);
    lv_obj_set_y(ui_AlarmDelBtn, 129);
    lv_obj_set_align(ui_AlarmDelBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AlarmDelBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AlarmDelBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_AlarmDelBtn, lv_color_hex(0x9A1006), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AlarmDelBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AlarmDelBtn, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_AlarmDelBtn);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Delete");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NewAlarmBtn = lv_btn_create(ui_Alarm);
    lv_obj_set_width(ui_NewAlarmBtn, 50);
    lv_obj_set_height(ui_NewAlarmBtn, 50);
    lv_obj_set_x(ui_NewAlarmBtn, 77);
    lv_obj_set_y(ui_NewAlarmBtn, 97);
    lv_obj_set_align(ui_NewAlarmBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NewAlarmBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NewAlarmBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NewAlarmBtn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_NewAlarmBtn);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "+");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Alarm, ui_event_Alarm, LV_EVENT_ALL, NULL);

}

void ui_Alarm_screen_destroy(void)
{
    if(ui_Alarm) lv_obj_del(ui_Alarm);

    // NULL screen variables
    ui_Alarm = NULL;
    ui_Alarm_container = NULL;
    ui_Set_alarm1 = NULL;
    ui_AlarmComp = NULL;
    ui_Alarm_Num1 = NULL;
    ui_Switch2 = NULL;
    ui_AlarmSetPanel = NULL;
    ui_RollerMin = NULL;
    ui_RollerHour = NULL;
    ui_Panel4 = NULL;
    ui_Panel9 = NULL;
    ui_Label4 = NULL;
    ui_Label9 = NULL;
    ui_AlarmSetBtn = NULL;
    ui_Label10 = NULL;
    ui_AlarmDelBtn = NULL;
    ui_Label17 = NULL;
    ui_NewAlarmBtn = NULL;
    ui_Label11 = NULL;

}
