// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_CLOCK_H
#define UI_CLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Clock
extern void ui_Clock_screen_init(void);
extern void ui_Clock_screen_destroy(void);
extern void ui_event_Clock(lv_event_t * e);
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_Clock_Number;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_ArcTask1;
extern lv_obj_t * ui_Task1min;
extern lv_obj_t * ui_ArcTask2;
extern lv_obj_t * ui_Task2min;
extern lv_obj_t * ui_ArcTask3;
extern lv_obj_t * ui_Task3min;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

