// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_CLOCK_H
#define UI_CLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Clock
extern void ui_Clock_screen_init(void);
extern void ui_Clock_screen_destroy(void);
extern void ui_event_Clock(lv_event_t * e);
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_Clock_Number;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_ArcTask1;
extern void ui_event_Task1min(lv_event_t * e);
extern lv_obj_t * ui_Task1min;
extern lv_obj_t * ui_ArcTask2;
extern void ui_event_Task2min(lv_event_t * e);
extern lv_obj_t * ui_Task2min;
extern lv_obj_t * ui_ArcTask3;
extern void ui_event_Task3min(lv_event_t * e);
extern lv_obj_t * ui_Task3min;
extern lv_obj_t * ui_TaskTimeSet;
extern lv_obj_t * ui_RollerTaskHr;
extern lv_obj_t * ui_RollerTaskMin;
extern lv_obj_t * ui_TaskHour;
extern lv_obj_t * ui_TaskMin;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_TaskSetBtn;
extern lv_obj_t * ui_Label20;
extern void ui_event_TaskBackBtn(lv_event_t * e);
extern lv_obj_t * ui_TaskBackBtn;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_TaskOnGoingPanel;
extern lv_obj_t * ui_TaskTimeHour;
extern lv_obj_t * ui_TaskTimeHourLabel;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_TaskTimeMin;
extern lv_obj_t * ui_TaskTimeMinLabel;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_TaskTimeSec;
extern lv_obj_t * ui_TaskTimeSecLabel;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_TaskTimePause;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

