// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_PRODUCTIVITY__H
#define UI_PRODUCTIVITY__H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Productivity_
extern void ui_Productivity__screen_init(void);
extern void ui_Productivity__screen_destroy(void);
extern lv_obj_t * ui_Productivity_;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_CalMonday;
extern lv_obj_t * ui_CalSunday;
extern lv_obj_t * ui_CalTuesday;
extern lv_obj_t * ui_CalWednesday;
extern lv_obj_t * ui_CalThursday;
extern lv_obj_t * ui_CalFriday;
extern lv_obj_t * ui_CalSaturday;
extern lv_obj_t * ui_CalenderHolder;
extern lv_obj_t * ui_Day;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label23;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

