// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * ui_Productivity_ = NULL;
lv_obj_t * ui_ProdCalender = NULL;
// event funtions

// build funtions

void ui_Productivity__screen_init(void)
{
    ui_Productivity_ = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Productivity_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Productivity_, &ui_img_dark_dotted2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Productivity_, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProdCalender = lv_calendar_create(ui_Productivity_);
    lv_calendar_set_today_date(ui_ProdCalender, 2026, 3, 21);
    lv_calendar_set_showed_date(ui_ProdCalender, 2026, 3);
    lv_obj_t * ui_ProdCalender_header = lv_calendar_header_arrow_create(ui_ProdCalender);
    lv_obj_set_width(ui_ProdCalender, 230);
    lv_obj_set_height(ui_ProdCalender, 240);
    lv_obj_set_align(ui_ProdCalender, LV_ALIGN_CENTER);

}

void ui_Productivity__screen_destroy(void)
{
    if(ui_Productivity_) lv_obj_del(ui_Productivity_);

    // NULL screen variables
    ui_Productivity_ = NULL;
    ui_ProdCalender = NULL;

}
