// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * ui_Productivity_ = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_CalMonth = NULL;
lv_obj_t * ui_CalMonday = NULL;
lv_obj_t * ui_CalSunday = NULL;
lv_obj_t * ui_CalTuesday = NULL;
lv_obj_t * ui_CalWednesday = NULL;
lv_obj_t * ui_CalThursday = NULL;
lv_obj_t * ui_CalFriday = NULL;
lv_obj_t * ui_CalSaturday = NULL;
lv_obj_t * ui_CalenderHolder = NULL;
lv_obj_t * ui_CalPrev = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_CalNext = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_CalYear = NULL;
lv_obj_t * ui_WifiCloseButton2 = NULL;
lv_obj_t * ui_Label12 = NULL;
// event funtions
void ui_event_WifiCloseButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 0, &ui_Clock_screen_init);
    }
}

// build funtions

void ui_Productivity__screen_init(void)
{
    ui_Productivity_ = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Productivity_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Productivity_, &ui_img_dark_dotted2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Productivity_, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Productivity_);
    lv_obj_set_width(ui_Panel6, 230);
    lv_obj_set_height(ui_Panel6, 270);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, -20);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalMonth = lv_label_create(ui_Productivity_);
    lv_obj_set_width(ui_CalMonth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalMonth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalMonth, 0);
    lv_obj_set_y(ui_CalMonth, -139);
    lv_obj_set_align(ui_CalMonth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalMonth, "December");
    lv_obj_set_style_text_color(ui_CalMonth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalMonth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalMonday = lv_label_create(ui_Productivity_);
    lv_obj_set_width(ui_CalMonday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalMonday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalMonday, -63);
    lv_obj_set_y(ui_CalMonday, -113);
    lv_obj_set_align(ui_CalMonday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalMonday, "Mo");
    lv_obj_set_style_text_color(ui_CalMonday, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalMonday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalSunday = lv_label_create(ui_Productivity_);
    lv_obj_set_width(ui_CalSunday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalSunday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalSunday, -95);
    lv_obj_set_y(ui_CalSunday, -113);
    lv_obj_set_align(ui_CalSunday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalSunday, "Su");
    lv_obj_set_style_text_color(ui_CalSunday, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalSunday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalTuesday = lv_label_create(ui_Productivity_);
    lv_obj_set_width(ui_CalTuesday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalTuesday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalTuesday, -31);
    lv_obj_set_y(ui_CalTuesday, -113);
    lv_obj_set_align(ui_CalTuesday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalTuesday, "Tu");
    lv_obj_set_style_text_color(ui_CalTuesday, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalTuesday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalWednesday = lv_label_create(ui_Productivity_);
    lv_obj_set_width(ui_CalWednesday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalWednesday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalWednesday, 1);
    lv_obj_set_y(ui_CalWednesday, -113);
    lv_obj_set_align(ui_CalWednesday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalWednesday, "We");
    lv_obj_set_style_text_color(ui_CalWednesday, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalWednesday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalThursday = lv_label_create(ui_Productivity_);
    lv_obj_set_width(ui_CalThursday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalThursday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalThursday, 33);
    lv_obj_set_y(ui_CalThursday, -113);
    lv_obj_set_align(ui_CalThursday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalThursday, "Th");
    lv_obj_set_style_text_color(ui_CalThursday, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalThursday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalFriday = lv_label_create(ui_Productivity_);
    lv_obj_set_width(ui_CalFriday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalFriday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalFriday, 65);
    lv_obj_set_y(ui_CalFriday, -113);
    lv_obj_set_align(ui_CalFriday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalFriday, "Fr");
    lv_obj_set_style_text_color(ui_CalFriday, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalFriday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalSaturday = lv_label_create(ui_Productivity_);
    lv_obj_set_width(ui_CalSaturday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalSaturday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalSaturday, 97);
    lv_obj_set_y(ui_CalSaturday, -113);
    lv_obj_set_align(ui_CalSaturday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalSaturday, "Sa");
    lv_obj_set_style_text_color(ui_CalSaturday, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalSaturday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalenderHolder = lv_obj_create(ui_Productivity_);
    lv_obj_remove_style_all(ui_CalenderHolder);
    lv_obj_set_width(ui_CalenderHolder, 228);
    lv_obj_set_height(ui_CalenderHolder, 194);
    lv_obj_set_x(ui_CalenderHolder, 0);
    lv_obj_set_y(ui_CalenderHolder, -4);
    lv_obj_set_align(ui_CalenderHolder, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CalenderHolder, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_CalenderHolder, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_CalenderHolder, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CalenderHolder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalenderHolder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalPrev = lv_btn_create(ui_Productivity_);
    lv_obj_set_width(ui_CalPrev, 25);
    lv_obj_set_height(ui_CalPrev, 25);
    lv_obj_set_x(ui_CalPrev, -98);
    lv_obj_set_y(ui_CalPrev, -138);
    lv_obj_set_align(ui_CalPrev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalPrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalPrev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CalPrev, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_CalPrev);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "<");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalNext = lv_btn_create(ui_Productivity_);
    lv_obj_set_width(ui_CalNext, 25);
    lv_obj_set_height(ui_CalNext, 25);
    lv_obj_set_x(ui_CalNext, 96);
    lv_obj_set_y(ui_CalNext, -138);
    lv_obj_set_align(ui_CalNext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CalNext, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_CalNext);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, ">");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalYear = lv_label_create(ui_Productivity_);
    lv_obj_set_width(ui_CalYear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalYear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalYear, 0);
    lv_obj_set_y(ui_CalYear, 103);
    lv_obj_set_align(ui_CalYear, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_CalYear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalYear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiCloseButton2 = lv_btn_create(ui_Productivity_);
    lv_obj_set_width(ui_WifiCloseButton2, 26);
    lv_obj_set_height(ui_WifiCloseButton2, 26);
    lv_obj_set_x(ui_WifiCloseButton2, 94);
    lv_obj_set_y(ui_WifiCloseButton2, 136);
    lv_obj_set_align(ui_WifiCloseButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiCloseButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiCloseButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiCloseButton2, lv_color_hex(0xACAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiCloseButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiCloseButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiCloseButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiCloseButton2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiCloseButton2, lv_color_hex(0xF4574C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_WifiCloseButton2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label12 = lv_label_create(ui_WifiCloseButton2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, -1);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "x");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WifiCloseButton2, ui_event_WifiCloseButton2, LV_EVENT_ALL, NULL);

}

void ui_Productivity__screen_destroy(void)
{
    if(ui_Productivity_) lv_obj_del(ui_Productivity_);

    // NULL screen variables
    ui_Productivity_ = NULL;
    ui_Panel6 = NULL;
    ui_CalMonth = NULL;
    ui_CalMonday = NULL;
    ui_CalSunday = NULL;
    ui_CalTuesday = NULL;
    ui_CalWednesday = NULL;
    ui_CalThursday = NULL;
    ui_CalFriday = NULL;
    ui_CalSaturday = NULL;
    ui_CalenderHolder = NULL;
    ui_CalPrev = NULL;
    ui_Label22 = NULL;
    ui_CalNext = NULL;
    ui_Label23 = NULL;
    ui_CalYear = NULL;
    ui_WifiCloseButton2 = NULL;
    ui_Label12 = NULL;

}
