// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_PRODUCTIVITY__H
#define UI_PRODUCTIVITY__H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Productivity_
extern void ui_Productivity__screen_init(void);
extern void ui_Productivity__screen_destroy(void);
extern void ui_event_Productivity_(lv_event_t * e);
extern lv_obj_t * ui_Productivity_;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_CalMonth;
extern lv_obj_t * ui_CalMonday;
extern lv_obj_t * ui_CalSunday;
extern lv_obj_t * ui_CalTuesday;
extern lv_obj_t * ui_CalWednesday;
extern lv_obj_t * ui_CalThursday;
extern lv_obj_t * ui_CalFriday;
extern lv_obj_t * ui_CalSaturday;
extern lv_obj_t * ui_CalenderHolder;
extern lv_obj_t * ui_CalPrev;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_CalNext;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_CalYear;
extern void ui_event_WifiCloseButton2(lv_event_t * e);
extern lv_obj_t * ui_WifiCloseButton2;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_DaysTask1;
extern lv_obj_t * ui_DaysTask2;
extern lv_obj_t * ui_DaysTask3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

