// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_PRODUCTIVITY__H
#define UI_PRODUCTIVITY__H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Productivity_
extern void ui_Productivity__screen_init(void);
extern void ui_Productivity__screen_destroy(void);
extern lv_obj_t * ui_Productivity_;
extern lv_obj_t * ui_ProdCalender;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

