// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * ui_Sketchpad = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_SketchCloseBtn = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_SketchSaveBtn = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions
void ui_event_SketchCloseBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Clock_screen_init);
    }
}

void ui_event_SketchSaveBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Clock_screen_init);
    }
}

// build funtions

void ui_Sketchpad_screen_init(void)
{
    ui_Sketchpad = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Sketchpad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_Sketchpad);
    lv_obj_set_width(ui_Panel5, 240);
    lv_obj_set_height(ui_Panel5, 320);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_panel_blue);
    ui_object_set_themeable_style_property(ui_Panel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_panel_blue);

    ui_Panel4 = lv_obj_create(ui_Sketchpad);
    lv_obj_set_width(ui_Panel4, 218);
    lv_obj_set_height(ui_Panel4, 291);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 11);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SketchCloseBtn = lv_btn_create(ui_Sketchpad);
    lv_obj_set_width(ui_SketchCloseBtn, 20);
    lv_obj_set_height(ui_SketchCloseBtn, 20);
    lv_obj_set_x(ui_SketchCloseBtn, 99);
    lv_obj_set_y(ui_SketchCloseBtn, -147);
    lv_obj_set_align(ui_SketchCloseBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SketchCloseBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SketchCloseBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SketchCloseBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SketchCloseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SketchCloseBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SketchCloseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SketchCloseBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SketchCloseBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SketchCloseBtn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Click_red);
    ui_object_set_themeable_style_property(ui_SketchCloseBtn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Click_red);

    ui_Label3 = lv_label_create(ui_SketchCloseBtn);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "X");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x020000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SketchSaveBtn = lv_btn_create(ui_Sketchpad);
    lv_obj_set_width(ui_SketchSaveBtn, 48);
    lv_obj_set_height(ui_SketchSaveBtn, 20);
    lv_obj_set_x(ui_SketchSaveBtn, -85);
    lv_obj_set_y(ui_SketchSaveBtn, -147);
    lv_obj_set_align(ui_SketchSaveBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SketchSaveBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SketchSaveBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SketchSaveBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SketchSaveBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SketchSaveBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SketchSaveBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SketchSaveBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SketchSaveBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SketchSaveBtn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_click_blue);
    ui_object_set_themeable_style_property(ui_SketchSaveBtn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_click_blue);

    ui_Label8 = lv_label_create(ui_SketchSaveBtn);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Save");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x020000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SketchCloseBtn, ui_event_SketchCloseBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SketchSaveBtn, ui_event_SketchSaveBtn, LV_EVENT_ALL, NULL);

}

void ui_Sketchpad_screen_destroy(void)
{
    if(ui_Sketchpad) lv_obj_del(ui_Sketchpad);

    // NULL screen variables
    ui_Sketchpad = NULL;
    ui_Panel5 = NULL;
    ui_Panel4 = NULL;
    ui_SketchCloseBtn = NULL;
    ui_Label3 = NULL;
    ui_SketchSaveBtn = NULL;
    ui_Label8 = NULL;

}
