// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * ui_SettingsNotes = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_NotesDisplayPanel = NULL;
lv_obj_t * ui_SettingsNoteCloseBtn = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_NotesViewPanel = NULL;
lv_obj_t * ui_SketchViewPanel = NULL;
lv_obj_t * ui_SketchViewCloseBtn = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_SketchViewDeleteBtn = NULL;
lv_obj_t * ui_Label15 = NULL;
// event funtions
void ui_event_SettingsNotes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        appc_notes_list_populate(e);
    }
}

void ui_event_SettingsNoteCloseBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Settings_screen_init);
    }
}

void ui_event_SketchViewCloseBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_NotesViewPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Settings_screen_init);
    }
}

void ui_event_SketchViewDeleteBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_NotesViewPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_SettingsNotes_screen_init(void)
{
    ui_SettingsNotes = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsNotes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel7 = lv_obj_create(ui_SettingsNotes);
    lv_obj_set_width(ui_Panel7, lv_pct(100));
    lv_obj_set_height(ui_Panel7, lv_pct(100));
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_panel_blue);
    ui_object_set_themeable_style_property(ui_Panel7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_panel_blue);
    lv_obj_set_style_bg_img_src(ui_Panel7, &ui_img_carbon_fibre_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Panel7, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NotesDisplayPanel = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_NotesDisplayPanel, lv_pct(92));
    lv_obj_set_height(ui_NotesDisplayPanel, lv_pct(85));
    lv_obj_set_x(ui_NotesDisplayPanel, 0);
    lv_obj_set_y(ui_NotesDisplayPanel, 15);
    lv_obj_set_align(ui_NotesDisplayPanel, LV_ALIGN_CENTER);

    ui_SettingsNoteCloseBtn = lv_btn_create(ui_Panel7);
    lv_obj_set_width(ui_SettingsNoteCloseBtn, 48);
    lv_obj_set_height(ui_SettingsNoteCloseBtn, 20);
    lv_obj_set_x(ui_SettingsNoteCloseBtn, 86);
    lv_obj_set_y(ui_SettingsNoteCloseBtn, -141);
    lv_obj_set_align(ui_SettingsNoteCloseBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsNoteCloseBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsNoteCloseBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsNoteCloseBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsNoteCloseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingsNoteCloseBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingsNoteCloseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsNoteCloseBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_SettingsNoteCloseBtn);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Close");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x070505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, -140);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Notes");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NotesViewPanel = lv_obj_create(ui_SettingsNotes);
    lv_obj_set_width(ui_NotesViewPanel, lv_pct(100));
    lv_obj_set_height(ui_NotesViewPanel, lv_pct(100));
    lv_obj_set_align(ui_NotesViewPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NotesViewPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_NotesViewPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_NotesViewPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_panel_blue);
    ui_object_set_themeable_style_property(ui_NotesViewPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_panel_blue);
    lv_obj_set_style_bg_img_src(ui_NotesViewPanel, &ui_img_carbon_fibre_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_NotesViewPanel, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SketchViewPanel = lv_obj_create(ui_NotesViewPanel);
    lv_obj_set_width(ui_SketchViewPanel, 218);
    lv_obj_set_height(ui_SketchViewPanel, 291);
    lv_obj_set_x(ui_SketchViewPanel, 0);
    lv_obj_set_y(ui_SketchViewPanel, -11);
    lv_obj_set_align(ui_SketchViewPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SketchViewPanel,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_SketchViewPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SketchViewPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SketchViewPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SketchViewCloseBtn = lv_btn_create(ui_NotesViewPanel);
    lv_obj_set_width(ui_SketchViewCloseBtn, 48);
    lv_obj_set_height(ui_SketchViewCloseBtn, 20);
    lv_obj_set_x(ui_SketchViewCloseBtn, 85);
    lv_obj_set_y(ui_SketchViewCloseBtn, 147);
    lv_obj_set_align(ui_SketchViewCloseBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SketchViewCloseBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SketchViewCloseBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SketchViewCloseBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SketchViewCloseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SketchViewCloseBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SketchViewCloseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SketchViewCloseBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SketchViewCloseBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SketchViewCloseBtn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Click_red);
    ui_object_set_themeable_style_property(ui_SketchViewCloseBtn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Click_red);

    ui_Label16 = lv_label_create(ui_SketchViewCloseBtn);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -1);
    lv_obj_set_y(ui_Label16, 0);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Close");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x020000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SketchViewDeleteBtn = lv_btn_create(ui_NotesViewPanel);
    lv_obj_set_width(ui_SketchViewDeleteBtn, 52);
    lv_obj_set_height(ui_SketchViewDeleteBtn, 20);
    lv_obj_set_x(ui_SketchViewDeleteBtn, -83);
    lv_obj_set_y(ui_SketchViewDeleteBtn, 147);
    lv_obj_set_align(ui_SketchViewDeleteBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SketchViewDeleteBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SketchViewDeleteBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SketchViewDeleteBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SketchViewDeleteBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SketchViewDeleteBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SketchViewDeleteBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SketchViewDeleteBtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SketchViewDeleteBtn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SketchViewDeleteBtn, lv_color_hex(0x4D97E3), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SketchViewDeleteBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label15 = lv_label_create(ui_SketchViewDeleteBtn);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Delete");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x020000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingsNoteCloseBtn, ui_event_SettingsNoteCloseBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SketchViewCloseBtn, ui_event_SketchViewCloseBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SketchViewDeleteBtn, ui_event_SketchViewDeleteBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsNotes, ui_event_SettingsNotes, LV_EVENT_ALL, NULL);

}

void ui_SettingsNotes_screen_destroy(void)
{
    if(ui_SettingsNotes) lv_obj_del(ui_SettingsNotes);

    // NULL screen variables
    ui_SettingsNotes = NULL;
    ui_Panel7 = NULL;
    ui_NotesDisplayPanel = NULL;
    ui_SettingsNoteCloseBtn = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_NotesViewPanel = NULL;
    ui_SketchViewPanel = NULL;
    ui_SketchViewCloseBtn = NULL;
    ui_Label16 = NULL;
    ui_SketchViewDeleteBtn = NULL;
    ui_Label15 = NULL;

}
