// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern void ui_event_settingsWifiPanel(lv_event_t * e);
extern lv_obj_t * ui_settingsWifiPanel;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_WifiEnableSwitch;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_InternetIndicator;
extern void ui_event_settingsNotesPanel(lv_event_t * e);
extern lv_obj_t * ui_settingsNotesPanel;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image4;
extern void ui_event_settingsTasksPanel(lv_event_t * e);
extern lv_obj_t * ui_settingsTasksPanel;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_TaskSelectPanel;
extern lv_obj_t * ui_Dropdown1;
extern void ui_event_TaskSelectBtn(lv_event_t * e);
extern lv_obj_t * ui_TaskSelectBtn;
extern lv_obj_t * ui_Label21;
extern void ui_event_TaskSelectBackBtn(lv_event_t * e);
extern lv_obj_t * ui_TaskSelectBackBtn;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_TaskTimeSet;
extern lv_obj_t * ui_RollerTaskHr2;
extern lv_obj_t * ui_RollerTaskMin2;
extern lv_obj_t * ui_TaskHour2;
extern lv_obj_t * ui_TaskMin2;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel13;
extern void ui_event_TaskSetBtn2(lv_event_t * e);
extern lv_obj_t * ui_TaskSetBtn2;
extern lv_obj_t * ui_Label27;
extern void ui_event_TaskBackBtn2(lv_event_t * e);
extern lv_obj_t * ui_TaskBackBtn2;
extern lv_obj_t * ui_Label25;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

