// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_SETTINGSNOTES_H
#define UI_SETTINGSNOTES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsNotes
extern void ui_SettingsNotes_screen_init(void);
extern void ui_SettingsNotes_screen_destroy(void);
extern lv_obj_t * ui_SettingsNotes;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_NotesDisplayPanel;
extern void ui_event_NoteTemplate(lv_event_t * e);
extern lv_obj_t * ui_NoteTemplate;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image3;
extern void ui_event_NoteEditBtn(lv_event_t * e);
extern lv_obj_t * ui_NoteEditBtn;
extern void ui_event_SettingsNoteCloseBtn(lv_event_t * e);
extern lv_obj_t * ui_SettingsNoteCloseBtn;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_NotesRenamePanel;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label10;
extern void ui_event_NoteRenameCancelBtn(lv_event_t * e);
extern lv_obj_t * ui_NoteRenameCancelBtn;
extern lv_obj_t * ui_Label11;
extern void ui_event_NoteRenameOkBtn(lv_event_t * e);
extern lv_obj_t * ui_NoteRenameOkBtn;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_RenameKeyboard;
extern lv_obj_t * ui_NotesViewPanel;
extern lv_obj_t * ui_SketchViewPanel;
extern void ui_event_SketchViewSaveBtn2(lv_event_t * e);
extern lv_obj_t * ui_SketchViewSaveBtn2;
extern lv_obj_t * ui_Label17;
extern void ui_event_SketchViewCloseBtn2(lv_event_t * e);
extern lv_obj_t * ui_SketchViewCloseBtn2;
extern lv_obj_t * ui_Label16;
extern void ui_event_SketchViewDeleteBtn1(lv_event_t * e);
extern lv_obj_t * ui_SketchViewDeleteBtn1;
extern lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

