// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_settingsWifiPanel = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_WifiEnableSwitch = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_InternetIndicator = NULL;
lv_obj_t * ui_settingsNotesPanel = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_settingsTasksPanel = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_TaskSelectPanel = NULL;
lv_obj_t * ui_TaskDropdown = NULL;
lv_obj_t * ui_TaskSelectBtn = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_TaskSelectBackBtn = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_PomodoroCheckbox = NULL;
lv_obj_t * ui_TaskTimeSet = NULL;
lv_obj_t * ui_RollerTaskHr = NULL;
lv_obj_t * ui_RollerTaskMin = NULL;
lv_obj_t * ui_TaskHour2 = NULL;
lv_obj_t * ui_TaskMin2 = NULL;
lv_obj_t * ui_Panel18 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_TaskSetBtn2 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_TaskBackBtn2 = NULL;
lv_obj_t * ui_Label25 = NULL;
// event funtions
void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Alarm, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_Alarm_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0, &ui_Clock_screen_init);
    }
}

void ui_event_settingsWifiPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Wifimenu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Wifimenu_screen_init);
    }
}

void ui_event_settingsNotesPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_SettingsNotes, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SettingsNotes_screen_init);
    }
}

void ui_event_settingsTasksPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TaskSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_TaskSelectBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TaskTimeSet, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_TaskSelectBackBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TaskSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_TaskSetBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TaskTimeSet, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TaskSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_TaskBackBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TaskTimeSet, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TaskSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Settings, &ui_img_carbon_fibre_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Settings, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsWifiPanel = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_settingsWifiPanel, 230);
    lv_obj_set_height(ui_settingsWifiPanel, 50);
    lv_obj_set_x(ui_settingsWifiPanel, 0);
    lv_obj_set_y(ui_settingsWifiPanel, -126);
    lv_obj_set_align(ui_settingsWifiPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settingsWifiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsWifiPanel, lv_color_hex(0x1C0D04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsWifiPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_settingsWifiPanel);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -78);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "WIFI");
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiEnableSwitch = lv_switch_create(ui_settingsWifiPanel);
    lv_obj_set_width(ui_WifiEnableSwitch, 50);
    lv_obj_set_height(ui_WifiEnableSwitch, 25);
    lv_obj_set_x(ui_WifiEnableSwitch, 78);
    lv_obj_set_y(ui_WifiEnableSwitch, 0);
    lv_obj_set_align(ui_WifiEnableSwitch, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_WifiEnableSwitch, lv_color_hex(0xBED8E1), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_WifiEnableSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_WifiEnableSwitch, lv_color_hex(0x4FA4EA), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_WifiEnableSwitch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Panel8 = lv_obj_create(ui_settingsWifiPanel);
    lv_obj_set_width(ui_Panel8, 20);
    lv_obj_set_height(ui_Panel8, 20);
    lv_obj_set_x(ui_Panel8, -37);
    lv_obj_set_y(ui_Panel8, 0);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xD4D7DA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel8, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InternetIndicator = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_InternetIndicator, 14);
    lv_obj_set_height(ui_InternetIndicator, 14);
    lv_obj_set_align(ui_InternetIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InternetIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_InternetIndicator, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InternetIndicator, lv_color_hex(0xF7F9FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InternetIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InternetIndicator, lv_color_hex(0x32B82D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_InternetIndicator, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_settingsNotesPanel = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_settingsNotesPanel, 230);
    lv_obj_set_height(ui_settingsNotesPanel, 50);
    lv_obj_set_x(ui_settingsNotesPanel, 0);
    lv_obj_set_y(ui_settingsNotesPanel, -67);
    lv_obj_set_align(ui_settingsNotesPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settingsNotesPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsNotesPanel, lv_color_hex(0x1C0D04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsNotesPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_settingsNotesPanel);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -78);
    lv_obj_set_y(ui_Label7, 0);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Notes");
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_settingsNotesPanel);
    lv_img_set_src(ui_Image4, &ui_img_565810218);
    lv_obj_set_width(ui_Image4, 32);
    lv_obj_set_height(ui_Image4, 32);
    lv_obj_set_x(ui_Image4, 78);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingsTasksPanel = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_settingsTasksPanel, 230);
    lv_obj_set_height(ui_settingsTasksPanel, 50);
    lv_obj_set_x(ui_settingsTasksPanel, 0);
    lv_obj_set_y(ui_settingsTasksPanel, -8);
    lv_obj_set_align(ui_settingsTasksPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settingsTasksPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsTasksPanel, lv_color_hex(0x1C0D04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsTasksPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_settingsTasksPanel);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -60);
    lv_obj_set_y(ui_Label20, 0);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Set Tasks");
    ui_object_set_themeable_style_property(ui_Label20, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_Label20, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TaskSelectPanel = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_TaskSelectPanel, 240);
    lv_obj_set_height(ui_TaskSelectPanel, 320);
    lv_obj_set_align(ui_TaskSelectPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TaskSelectPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_TaskSelectPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TaskSelectPanel, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TaskSelectPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TaskDropdown = lv_dropdown_create(ui_TaskSelectPanel);
    lv_dropdown_set_options(ui_TaskDropdown, "Task 1\nTask 2\nTask 3");
    lv_obj_set_width(ui_TaskDropdown, 200);
    lv_obj_set_height(ui_TaskDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TaskDropdown, 0);
    lv_obj_set_y(ui_TaskDropdown, -80);
    lv_obj_set_align(ui_TaskDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TaskDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_TaskDropdown, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TaskDropdown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_TaskDropdown), &lv_font_montserrat_34,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TaskSelectBtn = lv_btn_create(ui_TaskSelectPanel);
    lv_obj_set_width(ui_TaskSelectBtn, 100);
    lv_obj_set_height(ui_TaskSelectBtn, 50);
    lv_obj_set_x(ui_TaskSelectBtn, 0);
    lv_obj_set_y(ui_TaskSelectBtn, 79);
    lv_obj_set_align(ui_TaskSelectBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TaskSelectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TaskSelectBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_TaskSelectBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_TaskSelectBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_border_width(ui_TaskSelectBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_TaskSelectBtn);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "SET");
    ui_object_set_themeable_style_property(ui_Label21, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_Label21, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TaskSelectBackBtn = lv_btn_create(ui_TaskSelectPanel);
    lv_obj_set_width(ui_TaskSelectBackBtn, 60);
    lv_obj_set_height(ui_TaskSelectBackBtn, 25);
    lv_obj_set_x(ui_TaskSelectBackBtn, 0);
    lv_obj_set_y(ui_TaskSelectBackBtn, 132);
    lv_obj_set_align(ui_TaskSelectBackBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TaskSelectBackBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TaskSelectBackBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_TaskSelectBackBtn);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Back");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PomodoroCheckbox = lv_checkbox_create(ui_TaskSelectPanel);
    lv_checkbox_set_text(ui_PomodoroCheckbox, "  Pomodoro");
    lv_obj_set_width(ui_PomodoroCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PomodoroCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PomodoroCheckbox, 0);
    lv_obj_set_y(ui_PomodoroCheckbox, 8);
    lv_obj_set_align(ui_PomodoroCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PomodoroCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_PomodoroCheckbox, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PomodoroCheckbox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PomodoroCheckbox, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TaskTimeSet = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_TaskTimeSet, 240);
    lv_obj_set_height(ui_TaskTimeSet, 320);
    lv_obj_set_align(ui_TaskTimeSet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TaskTimeSet, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_TaskTimeSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TaskTimeSet, lv_color_hex(0x3C3C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TaskTimeSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerTaskHr = lv_roller_create(ui_TaskTimeSet);
    lv_roller_set_options(ui_RollerTaskHr, "00\n01\n02\n03\n04", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_RollerTaskHr, 100);
    lv_obj_set_width(ui_RollerTaskHr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_RollerTaskHr, -50);
    lv_obj_set_y(ui_RollerTaskHr, -67);
    lv_obj_set_align(ui_RollerTaskHr, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerTaskHr, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RollerTaskHr, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerTaskMin = lv_roller_create(ui_TaskTimeSet);
    lv_roller_set_options(ui_RollerTaskMin, "00\n10\n15\n30\n45", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_RollerTaskMin, 100);
    lv_obj_set_width(ui_RollerTaskMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_RollerTaskMin, 41);
    lv_obj_set_y(ui_RollerTaskMin, -67);
    lv_obj_set_align(ui_RollerTaskMin, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerTaskMin, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RollerTaskMin, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TaskHour2 = lv_label_create(ui_TaskTimeSet);
    lv_obj_set_width(ui_TaskHour2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TaskHour2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TaskHour2, -50);
    lv_obj_set_y(ui_TaskHour2, 13);
    lv_obj_set_align(ui_TaskHour2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TaskHour2, "Hr");
    lv_obj_set_style_text_color(ui_TaskHour2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TaskHour2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TaskHour2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TaskMin2 = lv_label_create(ui_TaskTimeSet);
    lv_obj_set_width(ui_TaskMin2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TaskMin2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TaskMin2, 43);
    lv_obj_set_y(ui_TaskMin2, 13);
    lv_obj_set_align(ui_TaskMin2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TaskMin2, "Min");
    lv_obj_set_style_text_color(ui_TaskMin2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TaskMin2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TaskMin2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_TaskTimeSet);
    lv_obj_set_width(ui_Panel18, 10);
    lv_obj_set_height(ui_Panel18, 10);
    lv_obj_set_x(ui_Panel18, -5);
    lv_obj_set_y(ui_Panel18, -80);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel18, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_TaskTimeSet);
    lv_obj_set_width(ui_Panel13, 10);
    lv_obj_set_height(ui_Panel13, 10);
    lv_obj_set_x(ui_Panel13, -5);
    lv_obj_set_y(ui_Panel13, -59);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TaskSetBtn2 = lv_btn_create(ui_TaskTimeSet);
    lv_obj_set_width(ui_TaskSetBtn2, 100);
    lv_obj_set_height(ui_TaskSetBtn2, 50);
    lv_obj_set_x(ui_TaskSetBtn2, 0);
    lv_obj_set_y(ui_TaskSetBtn2, 79);
    lv_obj_set_align(ui_TaskSetBtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TaskSetBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TaskSetBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_TaskSetBtn2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_TaskSetBtn2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_border_width(ui_TaskSetBtn2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_TaskSetBtn2);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "SET");
    ui_object_set_themeable_style_property(ui_Label27, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_Label27, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TaskBackBtn2 = lv_btn_create(ui_TaskTimeSet);
    lv_obj_set_width(ui_TaskBackBtn2, 60);
    lv_obj_set_height(ui_TaskBackBtn2, 25);
    lv_obj_set_x(ui_TaskBackBtn2, 0);
    lv_obj_set_y(ui_TaskBackBtn2, 132);
    lv_obj_set_align(ui_TaskBackBtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TaskBackBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TaskBackBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_TaskBackBtn2);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Back");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_settingsWifiPanel, ui_event_settingsWifiPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsNotesPanel, ui_event_settingsNotesPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsTasksPanel, ui_event_settingsTasksPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TaskSelectBtn, ui_event_TaskSelectBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TaskSelectBackBtn, ui_event_TaskSelectBackBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TaskSetBtn2, ui_event_TaskSetBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TaskBackBtn2, ui_event_TaskBackBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_settingsWifiPanel = NULL;
    ui_Label2 = NULL;
    ui_WifiEnableSwitch = NULL;
    ui_Panel8 = NULL;
    ui_InternetIndicator = NULL;
    ui_settingsNotesPanel = NULL;
    ui_Label7 = NULL;
    ui_Image4 = NULL;
    ui_settingsTasksPanel = NULL;
    ui_Label20 = NULL;
    ui_TaskSelectPanel = NULL;
    ui_TaskDropdown = NULL;
    ui_TaskSelectBtn = NULL;
    ui_Label21 = NULL;
    ui_TaskSelectBackBtn = NULL;
    ui_Label24 = NULL;
    ui_PomodoroCheckbox = NULL;
    ui_TaskTimeSet = NULL;
    ui_RollerTaskHr = NULL;
    ui_RollerTaskMin = NULL;
    ui_TaskHour2 = NULL;
    ui_TaskMin2 = NULL;
    ui_Panel18 = NULL;
    ui_Panel13 = NULL;
    ui_TaskSetBtn2 = NULL;
    ui_Label27 = NULL;
    ui_TaskBackBtn2 = NULL;
    ui_Label25 = NULL;

}
