// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_settingsWifiPanel = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_WifiEnableSwitch = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_InternetIndicator = NULL;
lv_obj_t * ui_settingsNotesPanel = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Image4 = NULL;
// event funtions
void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Alarm, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_Alarm_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0, 0, &ui_Clock_screen_init);
    }
}

void ui_event_settingsWifiPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Wifimenu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Wifimenu_screen_init);
    }
}

void ui_event_settingsNotesPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_SettingsNotes, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SettingsNotes_screen_init);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Settings, &ui_img_carbon_fibre_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Settings, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsWifiPanel = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_settingsWifiPanel, 230);
    lv_obj_set_height(ui_settingsWifiPanel, 50);
    lv_obj_set_x(ui_settingsWifiPanel, 0);
    lv_obj_set_y(ui_settingsWifiPanel, -126);
    lv_obj_set_align(ui_settingsWifiPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settingsWifiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsWifiPanel, lv_color_hex(0x1C0D04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsWifiPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_settingsWifiPanel);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -78);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "WIFI");
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_Label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiEnableSwitch = lv_switch_create(ui_settingsWifiPanel);
    lv_obj_set_width(ui_WifiEnableSwitch, 50);
    lv_obj_set_height(ui_WifiEnableSwitch, 25);
    lv_obj_set_x(ui_WifiEnableSwitch, 78);
    lv_obj_set_y(ui_WifiEnableSwitch, 0);
    lv_obj_set_align(ui_WifiEnableSwitch, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_WifiEnableSwitch, lv_color_hex(0xBED8E1), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_WifiEnableSwitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_WifiEnableSwitch, lv_color_hex(0x4FA4EA), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_WifiEnableSwitch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Panel8 = lv_obj_create(ui_settingsWifiPanel);
    lv_obj_set_width(ui_Panel8, 20);
    lv_obj_set_height(ui_Panel8, 20);
    lv_obj_set_x(ui_Panel8, -37);
    lv_obj_set_y(ui_Panel8, 0);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xD4D7DA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel8, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InternetIndicator = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_InternetIndicator, 14);
    lv_obj_set_height(ui_InternetIndicator, 14);
    lv_obj_set_align(ui_InternetIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InternetIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_InternetIndicator, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InternetIndicator, lv_color_hex(0xF7F9FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InternetIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InternetIndicator, lv_color_hex(0x32B82D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_InternetIndicator, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_settingsNotesPanel = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_settingsNotesPanel, 230);
    lv_obj_set_height(ui_settingsNotesPanel, 50);
    lv_obj_set_x(ui_settingsNotesPanel, 0);
    lv_obj_set_y(ui_settingsNotesPanel, -67);
    lv_obj_set_align(ui_settingsNotesPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settingsNotesPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsNotesPanel, lv_color_hex(0x1C0D04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsNotesPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_settingsNotesPanel);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -78);
    lv_obj_set_y(ui_Label7, 0);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Notes");
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_settingsNotesPanel);
    lv_img_set_src(ui_Image4, &ui_img_565810218);
    lv_obj_set_width(ui_Image4, 32);
    lv_obj_set_height(ui_Image4, 32);
    lv_obj_set_x(ui_Image4, 78);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_settingsWifiPanel, ui_event_settingsWifiPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsNotesPanel, ui_event_settingsNotesPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_settingsWifiPanel = NULL;
    ui_Label2 = NULL;
    ui_WifiEnableSwitch = NULL;
    ui_Panel8 = NULL;
    ui_InternetIndicator = NULL;
    ui_settingsNotesPanel = NULL;
    ui_Label7 = NULL;
    ui_Image4 = NULL;

}
