// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label2;
extern void ui_event_WifiEnableSwitch(lv_event_t * e);
extern lv_obj_t * ui_WifiEnableSwitch;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_InternetIndicator;
extern void ui_event_Panel6(lv_event_t * e);
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

