// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_SKETCHPAD_H
#define UI_SKETCHPAD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Sketchpad
extern void ui_Sketchpad_screen_init(void);
extern void ui_Sketchpad_screen_destroy(void);
extern lv_obj_t * ui_Sketchpad;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel4;
extern void ui_event_SketchCloseBtn(lv_event_t * e);
extern lv_obj_t * ui_SketchCloseBtn;
extern lv_obj_t * ui_Label3;
extern void ui_event_SketchSaveBtn(lv_event_t * e);
extern lv_obj_t * ui_SketchSaveBtn;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_NotesNamePanel;
extern lv_obj_t * ui_Panel10;
extern void ui_event_NoteNameCancelBtn(lv_event_t * e);
extern lv_obj_t * ui_NoteNameCancelBtn;
extern lv_obj_t * ui_Label18;
extern void ui_event_NoteNameOkBtn(lv_event_t * e);
extern lv_obj_t * ui_NoteNameOkBtn;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_NameKeyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

