// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_SETTINGSNOTES_H
#define UI_SETTINGSNOTES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsNotes
extern void ui_SettingsNotes_screen_init(void);
extern void ui_SettingsNotes_screen_destroy(void);
extern void ui_event_SettingsNotes(lv_event_t * e);
extern lv_obj_t * ui_SettingsNotes;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_NotesDisplayPanel;
extern void ui_event_SettingsNoteCloseBtn(lv_event_t * e);
extern lv_obj_t * ui_SettingsNoteCloseBtn;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_NotesViewPanel;
extern lv_obj_t * ui_SketchViewPanel;
extern void ui_event_SketchViewCloseBtn(lv_event_t * e);
extern lv_obj_t * ui_SketchViewCloseBtn;
extern lv_obj_t * ui_Label16;
extern void ui_event_SketchViewDeleteBtn(lv_event_t * e);
extern lv_obj_t * ui_SketchViewDeleteBtn;
extern lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

