// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * ui_Wifimenu = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_uiWifiList = NULL;
lv_obj_t * ui_uiWifiItemTemplate = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_SelectWifi = NULL;
lv_obj_t * ui_WifiCloseButton = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_WifiRefreshButton = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_uiPassPopup = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_WifiCancelButton = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_WifiConnectButton = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_uiPassTextArea = NULL;
lv_obj_t * ui_WifiPassKeyboard = NULL;
// event funtions
void ui_event_uiWifiItemTemplate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_wifi_item_clicked(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiPassPopup, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_WifiCloseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Settings_screen_init);
    }
}

void ui_event_WifiCancelButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiPassPopup, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_WifiConnectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_uiPassPopup, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_uiPassTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_WifiPassKeyboard,  ui_uiPassTextArea);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WifiPassKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

// build funtions

void ui_Wifimenu_screen_init(void)
{
    ui_Wifimenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Wifimenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Wifimenu);
    lv_obj_set_width(ui_Panel3, 197);
    lv_obj_set_height(ui_Panel3, 289);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xD9EAF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiWifiList = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_uiWifiList, 173);
    lv_obj_set_height(ui_uiWifiList, 235);
    lv_obj_set_x(ui_uiWifiList, 0);
    lv_obj_set_y(ui_uiWifiList, 16);
    lv_obj_set_align(ui_uiWifiList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_uiWifiList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uiWifiList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_uiWifiItemTemplate = lv_btn_create(ui_uiWifiList);
    lv_obj_set_height(ui_uiWifiItemTemplate, 24);
    lv_obj_set_width(ui_uiWifiItemTemplate, lv_pct(100));
    lv_obj_set_x(ui_uiWifiItemTemplate, 29);
    lv_obj_set_y(ui_uiWifiItemTemplate, -71);
    lv_obj_set_align(ui_uiWifiItemTemplate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiWifiItemTemplate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_uiWifiItemTemplate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uiWifiItemTemplate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uiWifiItemTemplate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uiWifiItemTemplate, lv_color_hex(0x0B0B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uiWifiItemTemplate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_uiWifiItemTemplate, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_uiWifiItemTemplate, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_uiWifiItemTemplate);
    lv_img_set_src(ui_Image1, &ui_img_1741635428);
    lv_obj_set_width(ui_Image1, lv_pct(14));
    lv_obj_set_height(ui_Image1, lv_pct(90));
    lv_obj_set_x(ui_Image1, -65);
    lv_obj_set_y(ui_Image1, -3);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 200);

    ui_Label4 = lv_label_create(ui_uiWifiItemTemplate);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SSID");

    ui_SelectWifi = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_SelectWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SelectWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SelectWifi, 9);
    lv_obj_set_y(ui_SelectWifi, 9);
    lv_label_set_text(ui_SelectWifi, "Select wifi");
    lv_obj_set_style_text_color(ui_SelectWifi, lv_color_hex(0x080000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SelectWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiCloseButton = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_WifiCloseButton, 26);
    lv_obj_set_height(ui_WifiCloseButton, 26);
    lv_obj_set_x(ui_WifiCloseButton, 65);
    lv_obj_set_y(ui_WifiCloseButton, -124);
    lv_obj_set_align(ui_WifiCloseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiCloseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiCloseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiCloseButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiCloseButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiCloseButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiCloseButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiCloseButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiCloseButton, lv_color_hex(0xF4574C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_WifiCloseButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label6 = lv_label_create(ui_WifiCloseButton);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "x");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiRefreshButton = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_WifiRefreshButton, 26);
    lv_obj_set_height(ui_WifiRefreshButton, 26);
    lv_obj_set_x(ui_WifiRefreshButton, 28);
    lv_obj_set_y(ui_WifiRefreshButton, -124);
    lv_obj_set_align(ui_WifiRefreshButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiRefreshButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiRefreshButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiRefreshButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiRefreshButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiRefreshButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiRefreshButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiRefreshButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WifiRefreshButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiRefreshButton, lv_color_hex(0xC4C7CB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_WifiRefreshButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image2 = lv_img_create(ui_WifiRefreshButton);
    lv_img_set_src(ui_Image2, &ui_img_refresh_64_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 75);
    ui_object_set_themeable_style_property(ui_Image2, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_click_blue);
    ui_object_set_themeable_style_property(ui_Image2, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_click_blue);

    ui_uiPassPopup = lv_obj_create(ui_Wifimenu);
    lv_obj_set_width(ui_uiPassPopup, 232);
    lv_obj_set_height(ui_uiPassPopup, 312);
    lv_obj_set_align(ui_uiPassPopup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiPassPopup, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_uiPassPopup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_uiPassPopup);
    lv_obj_set_width(ui_Panel1, 197);
    lv_obj_set_height(ui_Panel1, 94);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -90);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiCancelButton = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_WifiCancelButton, 55);
    lv_obj_set_height(ui_WifiCancelButton, 16);
    lv_obj_set_x(ui_WifiCancelButton, -6);
    lv_obj_set_y(ui_WifiCancelButton, 24);
    lv_obj_set_align(ui_WifiCancelButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiCancelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiCancelButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiCancelButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiCancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiCancelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiCancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiCancelButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WifiCancelButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiCancelButton, lv_color_hex(0xCBC7C7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_WifiCancelButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label1 = lv_label_create(ui_WifiCancelButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Back");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiConnectButton = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_WifiConnectButton, 55);
    lv_obj_set_height(ui_WifiConnectButton, 16);
    lv_obj_set_x(ui_WifiConnectButton, 60);
    lv_obj_set_y(ui_WifiConnectButton, 24);
    lv_obj_set_align(ui_WifiConnectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiConnectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiConnectButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiConnectButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiConnectButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WifiConnectButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_WifiConnectButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_click_blue);
    ui_object_set_themeable_style_property(ui_WifiConnectButton, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_click_blue);

    ui_Label5 = lv_label_create(ui_WifiConnectButton);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Connect");
    lv_label_set_recolor(ui_Label5, "true");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label5, lv_color_hex(0x5CC9EB), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_uiPassTextArea = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_uiPassTextArea, 150);
    lv_obj_set_height(ui_uiPassTextArea, LV_SIZE_CONTENT);    /// 17
    lv_obj_set_x(ui_uiPassTextArea, 0);
    lv_obj_set_y(ui_uiPassTextArea, -7);
    lv_obj_set_align(ui_uiPassTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_uiPassTextArea, "Password....");
    lv_textarea_set_one_line(ui_uiPassTextArea, true);
    lv_textarea_set_password_mode(ui_uiPassTextArea, true);
    lv_obj_set_style_outline_color(ui_uiPassTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_uiPassTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_uiPassTextArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_uiPassTextArea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiPassKeyboard = lv_keyboard_create(ui_uiPassPopup);
    lv_obj_set_width(ui_WifiPassKeyboard, 236);
    lv_obj_set_height(ui_WifiPassKeyboard, 162);
    lv_obj_set_x(ui_WifiPassKeyboard, 0);
    lv_obj_set_y(ui_WifiPassKeyboard, 76);
    lv_obj_set_align(ui_WifiPassKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiPassKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_uiWifiItemTemplate, ui_event_uiWifiItemTemplate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiCloseButton, ui_event_WifiCloseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiCancelButton, ui_event_WifiCancelButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiConnectButton, ui_event_WifiConnectButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_uiPassTextArea, ui_event_uiPassTextArea, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_WifiPassKeyboard, ui_uiPassTextArea);

}

void ui_Wifimenu_screen_destroy(void)
{
    if(ui_Wifimenu) lv_obj_del(ui_Wifimenu);

    // NULL screen variables
    ui_Wifimenu = NULL;
    ui_Panel3 = NULL;
    ui_uiWifiList = NULL;
    ui_uiWifiItemTemplate = NULL;
    ui_Image1 = NULL;
    ui_Label4 = NULL;
    ui_SelectWifi = NULL;
    ui_WifiCloseButton = NULL;
    ui_Label6 = NULL;
    ui_WifiRefreshButton = NULL;
    ui_Image2 = NULL;
    ui_uiPassPopup = NULL;
    ui_Panel1 = NULL;
    ui_WifiCancelButton = NULL;
    ui_Label1 = NULL;
    ui_WifiConnectButton = NULL;
    ui_Label5 = NULL;
    ui_uiPassTextArea = NULL;
    ui_WifiPassKeyboard = NULL;

}
