// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef UI_WIFIMENU_H
#define UI_WIFIMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Wifimenu
extern void ui_Wifimenu_screen_init(void);
extern void ui_Wifimenu_screen_destroy(void);
extern lv_obj_t * ui_Wifimenu;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_uiWifiList;
extern void ui_event_uiWifiItemTemplate(lv_event_t * e);
extern lv_obj_t * ui_uiWifiItemTemplate;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_SelectWifi;
extern void ui_event_WifiCloseButton(lv_event_t * e);
extern lv_obj_t * ui_WifiCloseButton;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_WifiRefreshButton;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_uiPassPopup;
extern lv_obj_t * ui_Panel1;
extern void ui_event_WifiCancelButton(lv_event_t * e);
extern lv_obj_t * ui_WifiCancelButton;
extern lv_obj_t * ui_Label1;
extern void ui_event_WifiConnectButton(lv_event_t * e);
extern lv_obj_t * ui_WifiConnectButton;
extern lv_obj_t * ui_Label5;
extern void ui_event_uiPassTextArea(lv_event_t * e);
extern lv_obj_t * ui_uiPassTextArea;
extern lv_obj_t * ui_WifiPassKeyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

