// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

lv_obj_t * ui_Weather = NULL;
lv_obj_t * ui_Pary_Cloud = NULL;
lv_obj_t * ui_New_York = NULL;
lv_obj_t * ui_Cloud = NULL;
lv_obj_t * ui_Celsius = NULL;
lv_obj_t * ui_Weather_Icons = NULL;
lv_obj_t * ui_w11 = NULL;
lv_obj_t * ui_w22 = NULL;
lv_obj_t * ui_w33 = NULL;
lv_obj_t * ui_W1_Num = NULL;
lv_obj_t * ui_W2_Num = NULL;
lv_obj_t * ui_W3_Num = NULL;
// event funtions
void ui_event_Weather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Clock_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Alarm, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Alarm_screen_init);
    }
}

// build funtions

void ui_Weather_screen_init(void)
{
    ui_Weather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Weather, &ui_img_dark_dotted2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Weather, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pary_Cloud = ui_Small_Label_create(ui_Weather);
    lv_obj_set_x(ui_Pary_Cloud, 0);
    lv_obj_set_y(ui_Pary_Cloud, -67);
    lv_obj_set_align(ui_Pary_Cloud, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pary_Cloud, "Partly cloudy");
    lv_obj_set_style_text_color(ui_Pary_Cloud, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pary_Cloud, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_New_York = ui_Small_Label_create(ui_Weather);
    lv_obj_set_x(ui_New_York, 0);
    lv_obj_set_y(ui_New_York, 37);
    lv_obj_set_align(ui_New_York, LV_ALIGN_CENTER);
    lv_label_set_text(ui_New_York, "New York");
    lv_obj_set_style_text_color(ui_New_York, lv_color_hex(0x8A3200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_New_York, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cloud = lv_img_create(ui_Weather);
    lv_img_set_src(ui_Cloud, &ui_img_cloud_png);
    lv_obj_set_width(ui_Cloud, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Cloud, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Cloud, -2);
    lv_obj_set_y(ui_Cloud, 19);
    lv_obj_set_align(ui_Cloud, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Cloud, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Cloud, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Celsius = lv_label_create(ui_Weather);
    lv_obj_set_width(ui_Celsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Celsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Celsius, 0);
    lv_obj_set_y(ui_Celsius, 125);
    lv_obj_set_align(ui_Celsius, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Celsius, "26°");
    ui_object_set_themeable_style_property(ui_Celsius, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Neon_orange);
    ui_object_set_themeable_style_property(ui_Celsius, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Neon_orange);
    lv_obj_set_style_text_font(ui_Celsius, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Icons = lv_obj_create(ui_Weather);
    lv_obj_set_height(ui_Weather_Icons, 56);
    lv_obj_set_width(ui_Weather_Icons, lv_pct(100));
    lv_obj_set_x(ui_Weather_Icons, 0);
    lv_obj_set_y(ui_Weather_Icons, -33);
    lv_obj_set_align(ui_Weather_Icons, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Weather_Icons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather_Icons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather_Icons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_w11 = lv_img_create(ui_Weather_Icons);
    lv_img_set_src(ui_w11, &ui_img_weather_1_png);
    lv_obj_set_width(ui_w11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_w11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_w11, 40);
    lv_obj_set_y(ui_w11, 0);
    lv_obj_add_flag(ui_w11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_w11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_w22 = lv_img_create(ui_Weather_Icons);
    lv_img_set_src(ui_w22, &ui_img_weather_2_png);
    lv_obj_set_width(ui_w22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_w22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_w22, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_w22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_w22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_w33 = lv_img_create(ui_Weather_Icons);
    lv_img_set_src(ui_w33, &ui_img_weather_3_png);
    lv_obj_set_width(ui_w33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_w33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_w33, -40);
    lv_obj_set_y(ui_w33, 0);
    lv_obj_set_align(ui_w33, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_w33, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_w33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_W1_Num = ui_Small_Label_create(ui_Weather_Icons);
    lv_obj_set_x(ui_W1_Num, 35);
    lv_obj_set_y(ui_W1_Num, 25);
    lv_obj_set_align(ui_W1_Num, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_W1_Num, "65°");
    lv_obj_set_style_text_color(ui_W1_Num, lv_color_hex(0x8A3200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_W1_Num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_W2_Num = ui_Small_Label_create(ui_Weather_Icons);
    lv_obj_set_x(ui_W2_Num, 0);
    lv_obj_set_y(ui_W2_Num, 25);
    lv_obj_set_align(ui_W2_Num, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_W2_Num, "24km/h");
    lv_obj_set_style_text_color(ui_W2_Num, lv_color_hex(0x8A3200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_W2_Num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_W3_Num = ui_Small_Label_create(ui_Weather_Icons);
    lv_obj_set_x(ui_W3_Num, -30);
    lv_obj_set_y(ui_W3_Num, 25);
    lv_obj_set_align(ui_W3_Num, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_W3_Num, "18%");
    lv_obj_set_style_text_color(ui_W3_Num, lv_color_hex(0x8A3200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_W3_Num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Weather, ui_event_Weather, LV_EVENT_ALL, NULL);

}

void ui_Weather_screen_destroy(void)
{
    if(ui_Weather) lv_obj_del(ui_Weather);

    // NULL screen variables
    ui_Weather = NULL;
    ui_Pary_Cloud = NULL;
    ui_New_York = NULL;
    ui_Cloud = NULL;
    ui_Celsius = NULL;
    ui_Weather_Icons = NULL;
    ui_w11 = NULL;
    ui_w22 = NULL;
    ui_w33 = NULL;
    ui_W1_Num = NULL;
    ui_W2_Num = NULL;
    ui_W3_Num = NULL;

}
